# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('decimal', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
